### ISSUE TITLE
[Feature Request] Supporting SQLModel

### ISSUE THREAD

**Issue by mbnoimi** [rafsaf/minimal-fastapi-postgres-template#13]
May you please add SQLModel supporting in this template or at least create a branch specifically for it?

We [discussed since two days](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/422#issuecomment-1188708123) ago about [SQLModel](https://sqlmodel.tiangolo.com/). I'm completely with SQLModel against duplicating codes for models (SQLAlchemy) and schemas (Pydantic) because IMHO duplicating code is kind of insanity. When I read about SQLModel for the first time I was really impressed (and I'm still) while you have some concerns about which are absolutely correct but may I think ignoring SQLModel completely is not fair for this fantastic package specially when you compare the neat syntax with the weird SQLAlchemy one.

In case you refused my request. I encourage you to add some wiki page or an example (2nd version of Pet ex.) in README.md shows how to use this template with SQLModel.

**Comment by kingyue737** [comment]
I think it makes sense as [SQLModel](https://github.com/tiangolo/sqlmodel) released a new version yesterday. Athough not actively maintained, it is likely still alive.

**Comment by rafsaf** [comment]
I think this is not an option, SQLAlchemy 2.0+ type support and is good enough and work they did - very impressive, I'm extremely suspicious about SQLModel, I wouldn't use it even for hobby project nor recommend it.
