### ISSUE TITLE
Question : Add Fastapi-users library for authentication ? 

### ISSUE THREAD

**Issue by sorasful** [rafsaf/minimal-fastapi-postgres-template#2]
I was asking myself if this would be a good idea to use this library : 

https://github.com/fastapi-users/fastapi-users 

Since it supports a lot of features out of the box, including oauth ...

What do you think ?

**Comment by sorasful** [comment]
Hmm, I finished reading the README.md and I understand your point of view, you want to keep it simple, without third party. 

I'm closing it, i'll reopen if you think we should do something about adding an option or something.

**Comment by rafsaf** [comment]
@sorasful 

That is definitely an option, currently user is prompted to enter the `project_name` only ;) I can not see any contraindications to add something optional, maybe one that it takes a bit of exercise, messing with if stmts in some files, or just keeping two versions for those files. I just didn't want crazy setup by default (and didn't need it really).


Let me look at it this or next weekend. 

If you have any thoughts, feel free to provide eg. repo based on this template with fastapi-users included, kicking it later into template is just an implementation detail.

**Comment by rafsaf** [comment]
Since [FastAPI Users](https://fastapi-users.github.io/fastapi-users/) started to support SQLAlchemy few weeks ago (and dropped support for `databases` library), I've added option to choose new template based on FastAPI Users in this repository.
