### ISSUE TITLE
Request: Get List of items.

### ISSUE THREAD

**Issue by paulr2021** [rafsaf/minimal-fastapi-postgres-template#4]
With this as an example, how would you return a list of items?

`@router.get("/", response_model=List[schemas.Cat])
    async def read_cat(
    cat: schemas.Cat,
    session: AsyncSession = Depends(deps.get_session),
    current_user: models.User = Depends(deps.get_current_user),
) -> List:
    """
    Get cats.
    """

    return cat`

**Comment by rafsaf** [comment]
Your question is not precise at all, I strongly suggest using precise words and proper code formatting when creating issues on GitHub ;) At least I can guess.

Standard way is to use SQLAlchemy ([1.4 style](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html)) query:

```python
@router.get("/", response_model=List[schemas.Cat])
async def read_cats(
    offset: int = 0,
    limit: int = 100,
    current_user: models.User = Depends(deps.get_current_user),
    session: AsyncSession = Depends(deps.get_session),
):
    """
    Get all cats
    """
    cats_result = await session.execute(select(models.Cat).offset(offset).limit(limit))
    return cats_result.scalars().all()
```
