### ISSUE TITLE
Question: Ruff + Black

### ISSUE THREAD

**Issue by renja-g** [rafsaf/minimal-fastapi-postgres-template#43]
Is Black still needed when using Ruff?

**Comment by rafsaf** [comment]
Looking here: https://astral.sh/blog/the-ruff-formatter, it is now drop-in replacement for black from end of Oct 2023, you are correct, `ruff format` should work just fine without black.

Thanks for creating an issue, I'm not sure if I'll be doing this in current 5.0 release of this repo, or just do it along with 6.0 branch that I'm working on (not very intensively to be honest, but now I will have few free weeks so definitely it will be looking at it).

**Comment by rafsaf** [comment]
done in https://github.com/rafsaf/minimal-fastapi-postgres-template/pull/44

black removed from dependencies
