### ISSUE TITLE
Pytest options in pyproject.toml

### ISSUE THREAD

**Issue by lybrain** [rafsaf/minimal-fastapi-postgres-template#51]
@rafsaf hello !
Could you please explain what does the following keys means ?
```
[tool.pytest.ini_options]
addopts = "-vv -n auto --cov --cov-report xml --cov-report term-missing --cov-fail-under=100"
```
From my understanding, `-n auto` sets number of workers to auto(based on CPU), and `--cov --cov-report xml --cov-report term-missing --cov-fail-under=100` we're using for coverage information, but what about `-vv` ?

**Comment by rafsaf** [comment]
Hello, you are correct for `-n auto` (that's for pytest-xdist, numer of processes) and coverage flags (pycoverage). As of `-vv` it's for pytest itself, shortcut for `--verbose`.

You can remove it completely, change to `-v` or even print more verbose output with `-vvv` if I remember correctly. Actually the same goes for other flags, this is just setup works for me.

**Comment by lybrain** [comment]
@rafsaf thank you for your answer !
